name: CinePulse Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build Project
        env: 
          TMDB_ACCESS_TOKEN: "${{ secrets.TMDB_ACCESS_TOKEN }}"
        run: |
          xcodebuild clean build \
            -project Cine-Pulse.xcodeproj \
            -scheme Cine-Pulse \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=26.0.1'
      - name: Run Tests
        env: 
          TMDB_ACCESS_TOKEN: "${{ secrets.TMDB_ACCESS_TOKEN }}"
        run: |
          xcodebuild test \
            -project Cine-Pulse.xcodeproj \
            -scheme Cine-Pulse \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=26.0.1'
            

